FROM hub.noths.com/ruby:2.2

RUN apt-get update && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ADD . $HOME

RUN bundle && \
    chmod +x $HOME/scripts/run_tests
# no-op command so the container does not shutdown
CMD true
