
CHROME_56:
  platform: "OS X 10.11"
  browserName: Chrome
  version: "56.0"

CHROME_55:
  platform: "OS X 10.11"
  browserName: Chrome
  version: "55.0"

FIREFOX_50:
  platform: "Windows 10"
  browserName: Firefox
  version: "50.0"

FIREFOX_51:
  platform: "Windows 10"
  browserName: Firefox
  version: "51.0"

IE_11:
  platform: "Windows 10"
  browserName: Internet Explorer
  version: "11.103"

IE_10:
  platform: "Windows 8"
  browserName: Internet Explorer
  version: "10.0"

SAFARI_10:
  platform: "OS X 10.11"
  browserName: Safari
  version: "10.0"

SAFARI_9:
  platform: "OS X 10.11"
  browserName: Safari
  version: "9.0"

IPHONE_6S_9.3:
  deviceName: iPhone 6s Plus Device
  deviceOrientation: portrait
  browserName:  Safari
  platformVersion: "9.3"
  platformName: iOS
  appiumVersion: '1.5.3'

IPHONE_6S_Simulator:
  deviceName: iPhone 6s Simulator
  deviceOrientation: portrait
  browserName:  Safari
  platformVersion: "9.3"
  platformName: iOS
  appiumVersion: '1.5.3'

IPHONE_5S_9.0:
  deviceName: iPhone 5s Simulator
  deviceOrientation: portrait
  browserName:  Safari
  platformVersion: "9.0"
  platformName: iOS

IPHONE_5_10.0:
  deviceName: iPhone 5 Simulator
  deviceOrientation: portrait
  browserName:  Safari
  platformVersion: "10.0"
  platformName: iOS

ANDROID_TAB_6.0:
  deviceName: Samsung Galaxy Note 5 Device
  deviceOrientation: portrait
  browserName:  chrome
  platformVersion: "6.0"
  platformName: Android

ANDROID_6_5.0:
  deviceName: Samsung Galaxy S5 Device
  deviceOrientation: portrait
  browserName:  chrome
  platformVersion: "5.0"
  platformName: Android